import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

function assert(value, message) {
  if (!value) throw new Error(message)
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const source = name => readFileSync(resolve(__dirname, `../src/${name}`), 'utf8')

const app = source('App.vue')
const documentSource = source('editor/document.ts')
const nodeRegistry = source('editor/nodeRegistry.ts')
const createEditor = source('editor/createEditor.ts')
const functionSignatureTypeOptionsStart = app.indexOf('const functionSignatureTypeOptions')
const functionSignatureTypeOptionsEnd = app.indexOf('const categories', functionSignatureTypeOptionsStart)
const functionSignatureTypeOptions = functionSignatureTypeOptionsStart >= 0 && functionSignatureTypeOptionsEnd > functionSignatureTypeOptionsStart
  ? app.slice(functionSignatureTypeOptionsStart, functionSignatureTypeOptionsEnd)
  : ''

assert(documentSource.includes("export type FunctionNodeRole = 'call' | 'entry' | 'return'"), 'document metadata must describe function node roles')
assert(documentSource.includes('functionSignature?: FunctionSignature'), 'node properties must persist the function signature snapshot')
assert(documentSource.includes('functionPath?: string'), 'node properties must persist workspace function paths')

assert(nodeRegistry.includes('export function createFunctionCallNode'), 'node registry must create function call nodes')
assert(nodeRegistry.includes('export function createFunctionEntryNode'), 'node registry must create function entry nodes')
assert(nodeRegistry.includes('export function createFunctionReturnNode'), 'node registry must create function return nodes')
assert(nodeRegistry.includes("result.addInput('exec'"), 'function call and return nodes must expose exec inputs')
assert(nodeRegistry.includes("result.addOutput('exec'"), 'function call and entry nodes must expose exec outputs')

assert(createEditor.includes('addFunctionCallNode(spec'), 'editor handle must expose addFunctionCallNode')
assert(createEditor.includes('addFunctionEntryNode(spec'), 'editor handle must expose addFunctionEntryNode')
assert(createEditor.includes('addFunctionReturnNode(spec'), 'editor handle must expose addFunctionReturnNode')
assert(createEditor.includes('syncFunctionSignature(spec'), 'editor handle must expose function signature synchronization')
assert(createEditor.includes('onFunctionSignature(value'), 'editor callbacks must report restored function signatures')
assert(createEditor.includes('emitFunctionSignatureFromSnapshot'), 'undo and redo must emit the restored function signature')
assert(createEditor.includes('functionNodePortsFromSnapshot'), 'function signature sync must calculate ports from the updated snapshot')
assert(createEditor.includes('pruneFunctionSignatureConnections'), 'function signature sync must prune connections to deleted parameters')
assert(createEditor.includes('data.connections = pruneFunctionSignatureConnections(data, changedNodeIds)'), 'deleted function ports must remove their old connections before restore')
assert(createEditor.includes("typeId.startsWith('origin.function.')"), 'restore must recognize persisted function nodes')
assert(createEditor.includes("typeof item.typeId === 'string'"), 'restore must not crash on legacy nodes without typeId')
assert(createEditor.includes('createRestoredNode(item, typeId'), 'restore must use a shared node restoration helper')
assert(createEditor.includes('item.properties?.legacyClass'), 'restore must fall back to legacy placeholders for unregistered migrated nodes')
assert(createEditor.includes('cloneFunctionSignatureFromProperties'), 'restore must safely clone empty function signature objects from legacy documents')
assert(!createEditor.includes('properties.functionSignature.inputs.map'), 'restore must not assume functionSignature.inputs exists')
assert(createEditor.includes('functionSignature: node.functionSignature'), 'snapshot must serialize function signatures')
assert(createEditor.includes('functionPropertiesForSnapshot(node)'), 'copy and snapshot must share function metadata serialization')

assert(app.includes('beginModuleItemPointerDrag($event, item)'), 'module library must route function drag through function-aware handler')
assert(app.includes('addModuleItemAt(item'), 'module library must route function double-click through function-aware creation')
assert(app.includes('syncFunctionSignatureToGraph'), 'signature edits must sync function entry and return nodes')
assert(app.includes('@change=\"syncFunctionSignatureToGraph\"'), 'signature editor changes must trigger graph synchronization')
assert(functionSignatureTypeOptions.includes("value: 'boolean'"), 'function signature ports must allow Boolean')
assert(functionSignatureTypeOptions.includes("value: 'integer'"), 'function signature ports must allow Integer')
assert(functionSignatureTypeOptions.includes("value: 'float'"), 'function signature ports must allow Float')
assert(functionSignatureTypeOptions.includes("value: 'string'"), 'function signature ports must allow String')
assert(functionSignatureTypeOptions.includes("value: 'array'"), 'function signature ports must allow Array')
assert(!functionSignatureTypeOptions.includes("'file'"), 'function signature ports must not allow File')
assert(!functionSignatureTypeOptions.includes("'table'"), 'function signature ports must not allow Table')
assert(!functionSignatureTypeOptions.includes("'dictionary'"), 'function signature ports must not allow Dictionary')
assert(app.includes('v-for=\"option in functionSignatureTypeOptions\"'), 'signature editor selects must use the function-specific type whitelist')
assert(app.includes('normalizeFunctionSignaturePortType'), 'loading signatures must normalize unsupported function parameter types')
assert(app.includes("const functionTitle = ref('')"), 'function blueprint details must track an editable title')
assert(app.includes('v-model=\"functionTitle\"'), 'function blueprint details must expose a title editor')
assert(app.includes('syncFunctionTitleToGraph'), 'editing a function title must sync the graph and references')
assert(app.includes('document.graphName = activeFunctionTitle()'), 'function title must persist as graphName instead of using the file name')
assert(app.includes('functionResourceTitle(entry)'), 'workspace function module names must use the saved function title')
assert(app.includes('loadFunctionLibraryTitles'), 'module library must load function titles from .obpf files')
assert(app.includes('activeFunctionTitle()'), 'function metadata must use the editable function title')
assert(app.includes('isSelfFunctionReference(item)'), 'function insertion must detect when a function references itself')
assert(app.includes("status.value = '函数不能引用自身'"), 'self function insertion must show a clear error')
assert(app.includes('if (isSelfFunctionReference(item))'), 'function insertion must stop before creating a self call node')
assert(app.includes('onFunctionSignature(value)'), 'function signature panel must listen for restored editor signatures')
assert(app.includes('functionSignature.value = normalizeFunctionSignature(value)'), 'undo and redo must restore the function signature editor state')
assert(app.includes('documentRequiresNativePersistence'), 'saveGraph must detect documents that cannot be represented as legacy VGF')
assert(app.includes('hasFunctionNodes(document)'), 'function nodes must force native persistence even for .vgf paths')
assert(app.includes('!documentRequiresNativePersistence(document)'), 'legacy export must be skipped when function nodes would be lost')
assert(app.includes('syncOpenFunctionReferences'), 'saving a function graph must refresh matching function call nodes in already-open tabs')
assert(app.includes('syncDocumentFunctionReferences'), 'inactive tab documents must update function metadata without being loaded in the editor')
assert(app.includes('await editor?.syncFunctionSignature('), 'the active editor must refresh visible function call ports after function save')
assert(app.includes('const blueprintFunctions = ref<BlueprintFunction[]>([])'), 'current blueprint functions must not create a confusing Default placeholder')
assert(app.includes("const selectedFunctionId = ref('')"), 'no current blueprint function should be selected by default')
assert(!app.includes("{ id: 'default', name: 'Default', readonly: true }"), 'Default current function placeholder should be removed')
assert(!app.includes('create-workspace-function'), 'workspace function creation should live in the file browser context menu')
assert(!app.includes('function-library-section'), 'workspace function management should not be duplicated in the left function panel')
assert(app.includes('createBlueprintInFileContext'), 'file browser context menu must create blueprint files in the selected folder')
assert(app.includes('createFunctionInFileContext'), 'file browser context menu must create function files in the selected folder')
assert(app.includes('openFileContextMenu($event, row.node)'), 'folders and files must both open the file browser context menu')
assert(app.includes('isFunction: isFunctionBlueprintPath(node.path)'), 'file browser context menu must detect function blueprint files')
assert(app.includes('fileContextMenu.isFunction ?'), 'file browser context menu must label function files as functions')
assert(app.includes('打开函数'), 'function file context menu must offer opening the function')
assert(app.includes('refreshDocumentFunctionReferencesOnOpen'), 'opening a graph must refresh function call nodes from referenced function files')
assert(app.includes('syncFunctionTerminalsFromDocumentSignature'), 'opening a function graph must refresh entry and return ports from the graph signature')
assert(app.includes('await refreshDocumentFunctionReferencesOnOpen(document, file.path)'), 'openGraph must refresh function signatures before loading the editor')
assert(app.includes('loadFunctionSignatureForPath'), 'openGraph refresh must read the latest workspace function signature from .obpf files')
assert(app.includes('loadFunctionSignatureForModuleItem'), 'workspace function call nodes must load signatures from .obpf files')
assert(app.includes('platform.openGraph(item.path)'), 'workspace function signatures must be read from the function file')
assert(app.includes('isNativeGraphDocument(parsed)'), 'openGraph must distinguish native documents from legacy-shaped files')
assert(app.includes('existing.document = document'), 'reopening an already-open graph must refresh stale tab contents')
assert(!app.includes('!item.functionPlaceholder && beginNodePointerDrag'), 'function placeholders must not disable pointer drag')
assert(!app.includes('!item.functionPlaceholder && addNodeAt'), 'function placeholders must not disable double-click creation')

console.log('functionNodes tests passed')
