import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

function assert(value, message) {
  if (!value) throw new Error(message)
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const app = readFileSync(resolve(__dirname, '../src/App.vue'), 'utf8')
const style = readFileSync(resolve(__dirname, '../src/style.css'), 'utf8')
const readme = readFileSync(resolve(__dirname, '../../README.md'), 'utf8')
const node = readFileSync(resolve(__dirname, '../src/editor/BlueprintNode.vue'), 'utf8')
const editor = readFileSync(resolve(__dirname, '../src/editor/createEditor.ts'), 'utf8')
const document = readFileSync(resolve(__dirname, '../src/editor/document.ts'), 'utf8')
const types = readFileSync(resolve(__dirname, '../src/editor/types.ts'), 'utf8')
const platform = readFileSync(resolve(__dirname, '../src/platform.ts'), 'utf8')
const appGo = readFileSync(resolve(__dirname, '../../app.go'), 'utf8')
const runBat = readFileSync(resolve(__dirname, '../../run.bat'), 'utf8')
const versionFile = readFileSync(resolve(__dirname, '../../VERSION'), 'utf8')
const zhCn = readFileSync(resolve(__dirname, '../src/i18n/zh-CN.ts'), 'utf8')
const enUs = readFileSync(resolve(__dirname, '../src/i18n/en-US.ts'), 'utf8')
const control = readFileSync(resolve(__dirname, '../src/editor/BlueprintControl.vue'), 'utf8')
const issueHighlightStart = editor.indexOf('async function highlightIssueNodes')
const issueHighlightEnd = editor.indexOf('async function highlightIssueNode', issueHighlightStart + 1)
const issueHighlight = issueHighlightStart >= 0 && issueHighlightEnd > issueHighlightStart ? editor.slice(issueHighlightStart, issueHighlightEnd) : ''
const selectGroupStart = editor.indexOf('async function selectGroup')
const selectGroupEnd = editor.indexOf('async function selectConnection', selectGroupStart + 1)
const selectGroupBody = selectGroupStart >= 0 && selectGroupEnd > selectGroupStart ? editor.slice(selectGroupStart, selectGroupEnd) : ''
const groupRenderStart = editor.indexOf('function renderGroups')
const groupRenderEnd = editor.indexOf('function updateGroupSelectionClasses', groupRenderStart + 1)
const groupRenderBody = groupRenderStart >= 0 && groupRenderEnd > groupRenderStart ? editor.slice(groupRenderStart, groupRenderEnd) : ''

assert(app.includes('查找目标：{{ nodeReferenceSearch.nodeTitle }}'), 'reference panel must show the searched node title')
assert(!app.includes('class="test-toolbar"'), 'top-right toolbar should not show a duplicate Test button')
assert(!app.includes('class="window-title"'), 'top menu bar should not show the centered Origin Blueprint title')
assert(!app.includes('runGraph'), 'frontend should not keep graph run entrypoints')
assert(!app.includes('stopGraph'), 'frontend should not keep graph stop entrypoints')
assert(!app.includes('executionRunning'), 'frontend should not keep execution running state')
assert(!app.includes('executionLogs'), 'frontend should not keep execution logs')
assert(app.includes('referencePanelCollapsed'), 'reference panel must support collapsing')
assert(app.includes('beginReferencePanelResize'), 'reference panel must support height resizing')
assert(app.includes('beginRightSidebarResize'), 'right sidebar width should be resizable')
assert(app.includes('beginLeftToolsResize'), 'function/variable/detail sidebar width should be resizable next to the canvas')
assert(app.includes('beginVariablePanelHeightResize'), 'variable/detail panels should be vertically resizable')
assert(app.includes('origin-blueprint-right-sidebar-width'), 'right sidebar width should persist locally')
assert(app.includes('origin-blueprint-left-tools-width'), 'function/variable/detail sidebar width should persist locally')
assert(!app.includes('origin-blueprint-function-panel-height'), 'removed function panel should not persist a stale height')
assert(app.includes('origin-blueprint-variable-panel-height'), 'variable panel height should persist locally')
assert(!app.includes('functionPanelStyle'), 'removed function panel should not bind a stale height style')
assert(app.includes('variablePanelStyle'), 'variable panel should bind a persisted height style')
assert(app.includes('interface BlueprintFunction'), 'function panel should have a lightweight function list model')
assert(app.includes('interface FunctionLibraryItem'), 'function library resources should have a lightweight list model')
assert(document.includes('interface FunctionSignature'), 'graph documents should define a function signature model')
assert(document.includes('functionSignature?: FunctionSignature'), 'function signatures should be optional native graph metadata')
assert(app.includes('blueprintFunctions'), 'function panel should keep the current-session function list')
assert(app.includes('functionLibraryItems'), 'app should track function library resources discovered in the workspace')
assert(app.includes('callableFunctionItems'), 'module library should expose callable function placeholders')
assert(app.includes('isFunctionResource'), 'workspace browser should recognize .obpf files and functions folders')
assert(!app.includes('selectWorkspaceFunction'), 'left function panel should not duplicate workspace function resources')
assert(!app.includes('openWorkspaceFunction'), 'workspace function resources should open through the file browser or module library')
assert(!app.includes('revealWorkspaceFunction'), 'workspace function resources should reveal through the file browser menu')
assert(!app.includes('createWorkspaceFunction'), 'workspace function creation should move to the file browser menu')
assert(app.includes('createBlueprintInFileContext'), 'file browser directory menu should create blueprint files')
assert(app.includes('createFunctionInFileContext'), 'file browser directory menu should create function files')
assert(app.includes('joinWorkspacePath(directory, `${graphName}.obpf`)'), 'file browser function creation should target the selected directory')
assert(app.includes('sanitizeFunctionFileName'), 'workspace function file names should be sanitized before saving')
assert(app.includes('functionSignature'), 'app should track the active function signature')
assert(app.includes('isFunctionBlueprintTab'), 'signature editor should only appear for function blueprint files')
assert(app.includes('addFunctionSignaturePort'), 'signature editor should support adding input and output ports')
assert(app.includes('removeFunctionSignaturePort'), 'signature editor should support removing signature ports')
assert(app.includes('normalizeFunctionSignature'), 'opening function files should normalize saved signatures')
assert(app.includes('document.functionSignature ='), 'saving function files should persist the active signature')
assert(app.includes('selectedFunctionId'), 'function selection state should remain available for editor clearing')
assert(app.includes('addBlueprintFunction'), 'current-session function helpers may remain while hidden from the left sidebar')
assert(app.includes('renameBlueprintFunction'), 'current-session function helpers may remain while hidden from the left sidebar')
assert(app.includes('removeBlueprintFunction'), 'current-session function helpers may remain while hidden from the left sidebar')
assert(!app.includes('当前蓝图函数'), 'left sidebar should not show the removed current-blueprint function panel')
assert(!app.includes('class=\"function-row\"'), 'removed function panel should not render function rows')
assert(!app.includes('class=\"add-function\"'), 'removed function panel should not expose an add function button')
assert(app.includes('class=\"workspace-icon function\"'), 'workspace browser should render function resources with a dedicated icon class')
assert(app.includes('class=\"function-library-empty\"'), 'module library should explain when no workspace function library is available')
assert(!app.includes('class=\"function-library-section\"'), 'left function panel should not duplicate workspace function resources')
assert(!app.includes('class=\"function-library-actions\"'), 'left function panel should not render workspace function row actions')
assert(!app.includes('class=\"function-library-panel-empty\"'), 'left function panel should not show a workspace function empty state')
assert(!app.includes('class=\"create-workspace-function\"'), 'left function panel should not show a create workspace function button')
assert(app.includes('function-signature-editor'), 'detail panel should expose a function signature editor')
assert(app.includes('函数签名'), 'function signature editor should be clearly labeled')
assert(!app.includes('@dblclick=\"openWorkspaceFunction(item)\"'), 'workspace function rows should no longer exist in the left panel')
assert(!app.includes('<label>Title<input v-model="selectedNode.label"'), 'ordinary node detail title should not be editable')
assert(app.includes('<label>Title<input :value="selectedNode.label" readonly'), 'ordinary node detail title should render as read-only information')
assert(app.includes('v-if="selectedNode.description"') && app.includes('<textarea :value="selectedNode.description" rows="4" readonly'), 'ordinary node detail description should render as read-only information')
assert(!app.includes('@click="applyNodeProperties"'), 'ordinary node detail should not expose Apply when no node fields are editable')
assert(!app.includes('updateSelectedNode(selectedNode.value.label'), 'ordinary node detail should not write node titles back to the editor')
assert(app.includes('category: menuText.value.module.functionCategory'), 'callable functions should appear as a Function category in the module library')
assert(!app.includes('functions:'), 'phase-one function panel must not write functions into GraphDocument yet')
assert(!app.includes('Input Defaults'), 'node detail panel should not show raw input defaults')
assert(editor.includes('setupMultiSelectionDragPreserver'), 'dragging a rubber-band multi-selection should keep the whole node set selected')
assert(editor.includes('restoreMultiSelectionAfterNodePick'), 'node pick should restore an existing multi-selection before dragging')
assert(editor.includes('toggleGroupSelected'), 'editor should expose a single group toggle command for Ctrl+G')
assert(editor.includes('async function clearGroupSelection'), 'editor should centralize clearing stale group selection')
assert(editor.includes('async function selectGroup'), 'selecting a group should switch away from node selection')
assert(editor.includes('function updateGroupSelectionClasses'), 'group selection should update classes without rebuilding group DOM')
assert(selectGroupBody.includes('updateGroupSelectionClasses()'), 'selecting a group should not rebuild the title DOM and break double-click rename')
assert(!selectGroupBody.includes('renderGroups()'), 'selecting a group should preserve the same DOM element so dblclick can fire')
assert(editor.includes('editingGroupId'), 'group titles should support inline editing state')
assert(groupRenderBody.includes("input.className = 'node-group-title-input'"), 'group title inline editor should render an input on double click')
assert(groupRenderBody.includes("event.key === 'Enter'"), 'group title inline editor should save on Enter')
assert(groupRenderBody.includes("event.key === 'Escape'"), 'group title inline editor should cancel on Escape')
assert(editor.includes('if (nodes.length) { await groupSelected(); return }'), 'Ctrl+G should create a new group when nodes are selected even if an old group selection is stale')
assert(editor.includes('await selector.unselectAll()\n      selectedGroupId = group.id; renderGroups()'), 'creating a group should leave the group selected instead of keeping its member nodes selected')
assert(editor.includes('clearGroupSelection()\n      start = null'), 'rubber-band selection should clear the previous group selection before the next Ctrl+G')
assert(editor.includes('clearGroupSelection()\n      startNodeDragFeedback()'), 'clicking a node should clear the previous group selection')
assert(app.includes('editor?.toggleGroupSelected()'), 'Ctrl+G and the menu should use the group toggle command')
assert(!app.includes('editor?.ungroupSelected())'), 'Ungroup should not require a separate Alt+G menu path')
assert(!app.includes("event.altKey && key === 'g'"), 'Alt+G should not be required for ungrouping selected groups')
assert(app.includes('currentLocale'), 'app should track the active menu locale')
assert(app.includes('menuText'), 'menu template should read labels from the locale file')
assert(app.includes('setLocale'), 'view menu should expose language switching')
assert(app.includes('showSettings'), 'app should expose a project settings dialog')
assert(app.includes('ProjectSettings'), 'app should use a structured project settings model')
assert(app.includes('loadProjectSettings'), 'opening a workspace should load originblueprint.project')
assert(app.includes('saveProjectSettings'), 'layout and display changes should save to originblueprint.project')
assert(app.includes('applyProjectSettings'), 'project settings should be applied to the current UI state')
assert(app.includes('projectSettingsContent'), 'app should keep normalized project settings content')
assert(app.includes('type ImageExportScale = 1 | 2 | 4'), 'project settings should offer useful PNG export scale choices')
assert(app.includes('export: { imageScale: ImageExportScale; showGrid: boolean }'), 'project settings should persist image export options')
assert(app.includes('projectSettingsContent.export.imageScale'), 'settings dialog should control image export scale')
assert(app.includes('projectSettingsContent.export.showGrid'), 'settings dialog should control grid visibility')
assert(app.includes('origin-blueprint-locale'), 'selected menu language should persist locally')
assert(zhCn.includes('显示左侧栏'), 'Chinese view menu should use the shorter left-sidebar label')
assert(!zhCn.includes('显示函数/变量/详情栏'), 'Chinese view menu left-sidebar label should not be overly long')
assert(zhCn.includes('语言'), 'Chinese menu text should include the language section label')
assert(zhCn.includes('图片导出倍率') && zhCn.includes('显示网格背景'), 'Chinese settings should include image export scale and grid visibility labels')
assert(zhCn.includes('节点') && zhCn.includes('代码'), 'Chinese validation panel should include structured issue labels')
assert(enUs.includes('Show Left Sidebar'), 'English view menu should include the shorter left-sidebar label')
assert(enUs.includes('Language'), 'English menu text should include the language section label')
assert(enUs.includes('Image Export Scale') && enUs.includes('Show grid background'), 'English settings should include image export scale and grid visibility labels')
assert(enUs.includes('Nodes') && enUs.includes('Code'), 'English validation panel should include structured issue labels')
assert(enUs.includes('File') && enUs.includes('Edit') && enUs.includes('View') && enUs.includes('Blueprint'), 'English locale should define the optimized top-level menu labels')
assert(!app.includes('<span class="chevron">⌄</span> 模块库'), 'module library panel title should be localized')
assert(!app.includes('placeholder="搜索模块..."'), 'module library search placeholder should be localized')
assert(app.includes('{{ menuText.module.title }}'), 'module library panel title should come from the locale file')
assert(app.includes(':placeholder="menuText.module.searchPlaceholder"'), 'module library search placeholder should come from the locale file')
assert(zhCn.includes("title: '模块库'") && zhCn.includes("searchPlaceholder: '搜索模块...'"), 'Chinese locale should define module library labels')
assert(enUs.includes("title: 'Module Library'") && enUs.includes("searchPlaceholder: 'Search modules...'"), 'English locale should define module library labels')
assert(!app.includes("toggleMenu('project')"), 'workspace actions should stay in the File menu instead of a top-level Project menu')
assert(enUs.includes("exportSelectedImage: 'Selected Nodes Image'"), 'English file menu should expose selected-node image export as a low-priority file action')
assert(enUs.includes("validate: 'Validate Blueprint'"), 'English blueprint menu should expose validation instead of a top-level Test button')
assert(enUs.includes("shortcuts: 'Shortcuts'") && enUs.includes("about: 'About OriginBlueprint'"), 'English help menu should split shortcuts and about entries')
assert(!enUs.includes('Shortcuts and About') && !zhCn.includes('快捷操作与关于'), 'help menu should not keep the old combined shortcuts/about label')
assert(app.includes('showShortcuts = true; activeMenu = null'), 'help menu should open a dedicated shortcuts dialog')
assert(app.includes('showAbout = true; activeMenu = null'), 'help menu should open a dedicated about dialog')
assert(app.includes('menuText.menu.file.openWorkspace'), 'file menu should contain the workspace folder action')
assert(app.includes('menuText.menu.file.refreshWorkspace'), 'file menu should contain a workspace refresh action')
assert(app.includes('menuText.menu.file.refreshNodeLibrary'), 'file menu should contain a node library refresh action')
assert(app.includes('collapseWorkspaceTree'), 'file browser should offer a collapse-all action')
assert(app.includes('revealActiveWorkspaceFile'), 'file browser should reveal the active opened file')
assert(app.includes('activeWorkspacePath.value === node.path'), 'file browser should mark the active opened file')
assert(app.includes("ctrl && event.shiftKey && key === 'q'"), 'Ctrl+Shift+Q should reveal the active blueprint file from tabs or the file browser')
assert(app.includes('run(() => revealCurrentFileInFolder(), event)'), 'Ctrl+Shift+Q should reveal the current file in the system file manager')
assert(app.indexOf("ctrl && event.shiftKey && key === 'q'") < app.indexOf("target.matches('input, textarea, select')"), 'Ctrl+Shift+Q should work even when focus is inside the file browser search field')
assert(app.includes('clearWorkspaceSelection()'), 'switching to an unsaved tab should clear stale file browser selection')
assert(app.includes('if (!path) { clearWorkspaceSelection(); return }'), 'active tab changes with no saved path should not leave the previous file selected')
assert(app.includes("workspaceSearch.value = ''"), 'revealing the active file should clear search so the selected file is visible')
assert(app.includes("document.querySelector('.workspace-entry.selected, .workspace-entry.active')?.scrollIntoView"), 'revealing the active file should scroll the selected file into view')
assert(app.includes('function selectedWorkspaceRevealPath()'), 'the reveal shortcut should support the file selected in the workspace browser')
assert(app.includes('return selectedWorkspaceRevealPath() || activeWorkspacePath.value'), 'workspace browser selection should be used before the active tab path for reveal in folder')
assert(app.includes('void revealWorkspaceFile(path, false)'), 'revealing in the system file manager should sync the workspace browser selection in the background')
assert(app.includes('await revealFileInFolder(path)'), 'Ctrl+Shift+Q should reuse the existing file-manager reveal behavior')
assert(app.indexOf('menuText.menu.file.openWorkspace') < app.indexOf('menuText.menu.file.recent'), 'workspace open should sit near Open before recent files')
assert(app.indexOf('menuText.menu.file.save') < app.indexOf('menuText.menu.file.refreshWorkspace'), 'refresh actions should not interrupt the common Save section')
assert(!app.includes("toggleMenu('project')"), 'workspace actions should not create a dedicated top-level Project menu')
assert(!app.includes("align('straighten')"), 'Align menu should not expose the confusing Straighten Edge command')
assert(!app.includes("key === 'q') run(() => editor?.align('straighten')"), 'Q should not remain bound to the removed straighten command')
assert(!zhCn.includes('straighten'), 'Chinese locale should not keep the removed straighten menu label')
assert(!enUs.includes('straighten'), 'English locale should not keep the removed straighten menu label')
assert(app.includes("toggleMenu('blueprint')"), 'top menu should include a dedicated Blueprint menu')
assert(app.includes("toggleMenu('help')"), 'top menu should render Help as a dropdown menu')
assert(!app.includes("toggleMenu('render')"), 'image export should no longer be a top-level Render menu')
assert(!app.includes('<button @click=\"run(testGraph)\">{{ menuText.menu.test }}</button>'), 'Validate/Test must not remain a standalone top-level button')
assert(!app.includes('<strong class="bottom-panel-target">Test Results</strong>'), 'validation results panel title should be localized')
assert(!app.includes('@click="testGraph">Test</button>'), 'validation results panel action should be localized')
assert(!app.includes('Right drag: pan'), 'canvas operation hint should be localized')
assert(app.includes('{{ menuText.canvas.hint }}'), 'canvas operation hint should come from the locale file')
assert(app.includes('{{ menuText.validation.title }}'), 'validation results title should come from the locale file')
assert(app.includes('{{ menuText.toolbar.test }}'), 'validation results rerun button should reuse the localized test label')
assert(zhCn.includes('canvas:') && zhCn.includes('右键拖拽'), 'Chinese locale should define the canvas operation hint')
assert(zhCn.includes('validation:') && zhCn.includes('检查结果'), 'Chinese locale should define validation results labels')
assert(enUs.includes('canvas:') && enUs.includes('Right drag: pan'), 'English locale should define the canvas operation hint')
assert(enUs.includes('validation:') && enUs.includes('Test Results'), 'English locale should define validation results labels')
assert(app.includes('v-if=\"platform.isDesktop()\"'), 'desktop-only menu actions should be hidden outside the Wails desktop runtime')
assert(app.includes('refreshNodeLibrary'), 'menu should refresh runtime node definitions without restarting the app')
assert(app.includes("ctrl && event.altKey && key === 'r'"), 'selected-node image export shortcut should be wired')
assert(app.includes("ctrl && event.shiftKey && key === 'r'"), 'whole-graph image export shortcut should be wired')
assert(app.includes('const path = await platform.chooseExportPNGPath(graphDirectoryForExport())'), 'image export should ask for the save path before rendering the PNG and use the graph directory')
assert(app.includes('await platform.savePNG(path, data)'), 'image export should save to the chosen path after rendering')
assert(app.includes('function exportImageBounds'), 'image export should crop to actual graph content instead of the full viewport')
assert(app.includes('function graphDirectoryForExport'), 'image export should prefer the current graph directory for the save dialog')
assert(app.includes('const exportImagePadding = 64'), 'image export should leave a readable margin around cropped blueprint content')
assert(app.includes('const x = Math.floor(bounds.x - exportImagePadding)'), 'image export padding should be allowed to extend beyond the current viewport edge')
assert(app.includes('const data = await toPng(canvas.value'), 'image export should rasterize the actual DOM graph directly')
assert(!app.includes('function prepareCanvasForImageExport'), 'image export must not hide real SVG connections before rasterizing')
assert(!app.includes('function captureExportConnections'), 'image export must not capture SVG paths for a second drawing pass')
assert(!app.includes('function composeExportImage'), 'image export must not composite a separate canvas layer')
assert(!app.includes('function drawExportConnections'), 'image export must not redraw connections with mismatched canvas coordinates')
assert(!app.includes('new Path2D(connection.path)'), 'image export must not redraw captured connection paths with Canvas Path2D')
assert(!app.includes('line.getScreenCTM()'), 'image export should not depend on screen matrices for PNG connection rendering')
assert(app.includes('function prepareConnectionDomForImageExport'), 'image export should sanitize the real DOM connection paths before rasterizing')
assert(app.includes("root.querySelectorAll<SVGPathElement>('.connection-hit-area')"), 'image export should physically hide transparent hit-area paths')
assert(app.includes("path.setAttribute('d', '')"), 'image export should clear hit-area geometry so html-to-image cannot render it as black strokes')
assert(app.includes("setImportantStyle(line, 'stroke', color)"), 'image export should inline the resolved connection color')
assert(app.includes("setImportantStyle(line, 'stroke-width', width)"), 'image export should inline stable connection stroke widths')
assert(app.includes('const pixelRatio = projectSettingsContent.value.export.imageScale'), 'image export should use the project export scale setting')
assert(appGo.includes('LastExportDirectory string') && appGo.includes('recordExportDirectory(path)'), 'PNG export should remember the last save directory')
assert(app.includes('void revealWorkspaceFile(path, false)'), 'revealing a file in Explorer should not wait for the sidebar tree to expand first')
assert(!app.includes('showEmptyStart'), 'the first-run empty state should be removed')
assert(!app.includes('empty-start-panel'), 'the first-run empty panel should not render')
assert(!app.includes('openSampleProject'), 'the removed first-run guide should not keep a sample project shortcut')
assert(!style.includes('.empty-start-panel'), 'first-run guide styles should be removed')
assert(!zhCn.includes('emptyStart') && !enUs.includes('emptyStart'), 'locale files should not keep unused empty-start labels')
assert(readFileSync(resolve(__dirname, '../../.github/workflows/ci.yml'), 'utf8').includes('npm run test:layout'), 'GitHub Actions CI should run frontend layout tests')
assert(app.includes("canvas.value.classList.add('exporting-image')"), 'image export should enable export-specific canvas styling')
assert(app.includes("canvas.value.classList.remove('exporting-image')"), 'image export should always clear export-specific canvas styling')
assert(style.includes('.rete-canvas.exporting-image .connection-line'), 'image export should disable connection filters that render as black strokes')
assert(style.includes('.rete-canvas.exporting-image .connection-hit-area'), 'image export should hide transparent connection hit areas from PNG output')
assert(style.includes('.status-bar span:first-child'), 'status bar message should be more visually prominent')
assert(!app.includes('Show Logger'), 'view menu should not show the old English logger label')
assert(!app.includes('Show Tool Sidebar'), 'view menu should not show the old generic tool sidebar label')
assert(!app.includes('Show Right Sidebar'), 'view menu should not show the old generic right sidebar label')
assert(app.includes('openFileContextMenu($event, result)'), 'reference results should open a file context menu on right click')
assert(app.includes('openFileContextMenu($event, row.node)'), 'workspace files and folders should open a file context menu on right click')
assert(app.includes('openFileContextGraph'), 'file context menu should offer opening the blueprint')
assert(app.includes('refreshFileContextDirectory'), 'file context menu should offer refreshing stale workspace directories')
assert(app.includes('refreshWorkspaceDirectory'), 'workspace directory refresh should reload the selected directory contents')
assert(app.includes('ensureWorkspaceChildren(node, workspaceNodeDepth(node.path) + 1, true)'), 'reopening a cached workspace directory should refresh deleted files')
assert(app.includes('refreshWorkspaceVisibleDirectories'), 'workspace browser should refresh already-expanded directories when files change externally')
assert(app.includes('origin-blueprint-workspace-refresh-interval'), 'workspace browser should use a named refresh interval for expanded directories')
assert(app.includes("window.addEventListener('focus', refreshWorkspaceOnFocus)"), 'workspace browser should refresh when the app regains focus after external file deletes')
assert(app.includes('createBlueprintInFileContext'), 'directory context menu should offer creating a blueprint')
assert(app.includes('createFunctionInFileContext'), 'directory context menu should offer creating a function')
assert(app.includes('revealFileContextInFolder'), 'file context menu should offer revealing the file location')
assert(!app.includes('@contextmenu.stop.prevent="revealFileInFolder(result.path)"'), 'reference result right click must not directly reveal files')
assert(!app.includes('@contextmenu.stop.prevent="!row.node.isDir && revealFileInFolder(row.node.path)"'), 'workspace right click must not directly reveal files')

assert(style.includes('.bottom-panel-resizer'), 'reference panel needs a resize handle')
assert(style.includes('.panel-height-splitter'), 'left sidebar panels need visible resize splitters')
assert(style.includes('.right-sidebar-splitter'), 'right sidebar needs a visible resize splitter')
assert(style.includes('.left-tools-splitter'), 'function/variable/detail sidebar needs a canvas resize splitter')
assert(style.includes('var(--right-sidebar-width'), 'workspace grid should use the persisted right sidebar width')
assert(style.includes('var(--left-tools-width'), 'workspace grid should use the persisted function/variable/detail width')
assert(style.includes('.bottom-panel.collapsed'), 'reference panel needs collapsed styling')
assert(style.includes('width: 28px; height: 24px'), 'reference panel controls should be compact but easy to click')
assert(style.includes('.bottom-panel-tool-button.close:hover'), 'close button should have a distinct hover state')
assert(style.includes('.file-context-menu'), 'file context menu needs styling')
assert(style.includes('max-height: calc(100vh - 42px)'), 'dropdown menus should scroll when the window is short')
assert(style.includes('.workspace { min-height: 0; flex: 1; overflow: hidden;'), 'main workspace should clip panels so the file tree can own vertical scrolling')
assert(style.includes('.sidebar { min-width: 0; min-height: 0; overflow: hidden;'), 'sidebars should not grow past the viewport when their content expands')
assert(style.includes('.sidebar-file-browser .workspace-panel { min-height: 0; flex: 1;'), 'file browser panel should shrink to the available sidebar height')
assert(style.includes('.workspace-tree::-webkit-scrollbar'), 'workspace tree should expose a visible scrollbar style')
assert(style.includes('scrollbar-width: thin'), 'workspace tree should show a visible scrollbar in browsers with standard scrollbar styling')
assert(style.includes('scrollbar-gutter: stable'), 'workspace tree should reserve scrollbar space for deep expanded folders')
assert(app.includes('https://api.github.com/repos/duanhf2012/OriginBlueprint/releases/latest'), 'update checks should use the GitHub latest release API')
assert(app.includes("import.meta.env.VITE_APP_VERSION || '0.0.0'"), 'app version should be injected at build time for release comparison')
assert(runBat.includes('set "VITE_APP_VERSION=%APP_VERSION%"'), 'run.bat should inject the release version into the frontend build')
assert(runBat.includes('set /p APP_VERSION=<"%CD%\\VERSION"'), 'run.bat should read the default release version from VERSION')
assert(/^\d+\.\d+\.\d+\s*$/.test(versionFile), 'VERSION should contain a semver release number')
assert(app.includes('origin-blueprint-auto-check-updates'), 'automatic update checks should be user-configurable')
assert(app.includes('function checkForUpdates'), 'settings should expose a manual update check')
assert(app.includes('menuText.about.checkUpdates') && app.includes('@click="checkForUpdates(true)"'), 'about dialog should expose manual version checking')
assert(app.includes('platform.openExternalURL'), 'update prompts should open the GitHub release page through the platform layer')
assert(platform.includes('OpenExternalURL(url: string)'), 'desktop platform bridge should expose external URL opening')
assert(appGo.includes('func (a *App) OpenExternalURL') && appGo.includes('runtime.BrowserOpenURL'), 'Wails backend should open update release URLs in the browser')
assert(zhCn.includes('自动检查更新') && enUs.includes('Check for updates automatically'), 'update settings labels should be localized')
assert(zhCn.includes('检查版本') && enUs.includes('Check Version'), 'about version check labels should be localized')
assert(style.includes('--workspace-font-size: 13px'), 'normal UI scale should define the baseline workspace tree font')
assert(style.includes('--workspace-font-size: 14px'), 'large UI scale should make workspace tree text larger than normal')
assert(style.includes('font-size: var(--workspace-font-size)'), 'workspace file tree entries should follow the UI scale setting')
assert(style.includes('--module-font-size: 12px'), 'normal UI scale should define module library font size')
assert(style.includes('--module-font-size: 13px'), 'large UI scale should make module library text larger than normal')
assert(style.includes('font: var(--module-font-weight, 400) var(--module-font-size)'), 'module categories should follow UI scale variables')
assert(style.includes('font-size: var(--detail-font-size)'), 'node detail panel should follow UI scale variables')
assert(style.includes('font-size: var(--settings-font-size)'), 'settings dialog should follow UI scale variables')
assert(style.includes('.node-detail input[readonly], .node-detail textarea[readonly]'), 'read-only node detail fields should have a distinct non-editable style')
assert(style.includes('.workspace-icon.function'), 'function resources need a distinct workspace icon')
assert(style.includes('.workspace-actions'), 'file browser needs a compact action area')
assert(style.includes('.settings-dialog'), 'project settings dialog needs styling')
assert(style.includes('.application-shell.grid-hidden .rete-canvas'), 'grid visibility setting should hide the canvas grid without removing the canvas background')
assert(style.includes('.logger-issue-meta'), 'validation issues should expose structured metadata styling')
assert(style.includes('.node-group-title-input'), 'inline group title editing needs styling')
assert(style.includes('.function-library-empty'), 'function library empty state needs styling')
assert(!style.includes('.function-library-section'), 'removed left function library section should not keep styling')
assert(!style.includes('.function-library-actions'), 'removed workspace function row actions should not keep styling')
assert(!style.includes('.function-library-panel-empty'), 'removed left function library empty state should not keep styling')
assert(style.includes('.function-signature-editor'), 'function signature editor needs styling')
assert(style.includes('.signature-port-row'), 'function signature port rows need styling')

assert(types.includes('referenceHighlighted?: boolean'), 'blueprint nodes need an independent reference highlight state')
assert(!types.includes('executionState'), 'nodes should not keep UI execution state when local running is disabled')
assert(node.includes("'reference-highlighted': data.referenceHighlighted"), 'node template must render reference highlight state')
assert(node.includes('font: var(--node-title-font-size, 16px) Arial'), 'node title font should follow node scale settings')
assert(node.includes('font: var(--node-port-font-size, 12px) Consolas'), 'node port font should follow node scale settings')
assert(node.includes('font: var(--node-badge-font-size, 10px)'), 'node badges should follow node scale settings')
assert(node.includes('font: var(--node-control-font-size, 11px) Consolas'), 'dynamic branch controls should follow node scale settings')
assert(control.includes('font: var(--node-control-font-size, 12px) Consolas'), 'inline node controls should follow node scale settings')
assert(!node.includes('execution-running'), 'node styles should not keep running highlights when local running is disabled')
assert(node.includes('#ffd21f'), 'reference highlight should use bright yellow for visibility')
assert(!node.includes('.blueprint-node.reference-highlighted { outline: 3px solid #f04444'), 'reference highlight must not reuse the error color')
assert(types.includes('legacyStyle?: boolean'), 'legacy metadata must be separate from legacy visual styling')
assert(node.includes('legacy: Boolean(data.legacyStyle)'), 'legacy styling must use an explicit visual flag')
assert(!node.includes('legacy: Boolean(data.legacyClass)'), 'runtime nodes with legacy metadata must not all render as legacy-styled')
assert(!node.includes('.blueprint-node.legacy { --accent:'), 'legacy compat styling must not override node kind colors')
assert(!node.includes('legacy-badge') && !node.includes('COMPAT'), 'legacy compat nodes should not show the developer-facing COMPAT badge')
assert(editor.includes('node.referenceHighlighted'), 'reference search should mark nodes with the independent highlight state')
assert(!editor.includes('setExecutionStates'), 'editor handle should not expose execution-state updates when local running is disabled')
assert(!editor.includes('for (const node of matches) await selectable.select(node.id, true)'), 'reference search should not rely on selection yellow for highlighting')
assert(editor.includes('const issueHighlightZoomScale'), 'issue highlighting should use a dedicated zoom scale')
assert(editor.includes('const nodeLocateZoomScale'), 'node lookup should use a fixed readable zoom scale')
assert(editor.includes('const nodeLocateMinZoomScale'), 'multi-node lookup should have a readable minimum zoom scale')
assert(editor.includes('const nodeLocateViewportAnchor'), 'node lookup should place targets in the upper reading area')
assert(editor.includes('async function centerNodesForReading'), 'node lookup should center targets without maximizing them')
assert(editor.includes('await centerNodesForReading(matches)'), 'reference lookup should use readable centering')
assert(!issueHighlight.includes('AreaExtensions.zoomAt(area, matches'), 'issue highlighting must not maximize the target nodes')
assert(!issueHighlight.includes('selectable.select'), 'issue highlighting must not select nodes and flash the yellow selection outline')
assert(app.includes('const ids = issueNodeIds(issue)'), 'validation issue selection must derive targets from issue node ids')
assert(app.includes('await editor.highlightIssueNodes([])'), 'running Test must clear stale issue highlights before showing new results')
assert(app.includes('let validationIssueClickTimer'), 'validation issue clicks should be delayed so double-click does not flash single-click selection')
assert(app.includes('clearValidationIssueClickTimer()'), 'validation issue double-click should cancel pending single-click focus')
assert(issueHighlight.includes('const idSet = new Set(ids.filter(Boolean))'), 'issue highlighting must build an exact id set')
assert(issueHighlight.includes('editor.getNodes().filter(node => idSet.has(node.id))'), 'issue highlighting must match node ids exactly')
assert(!issueHighlight.includes('node.label'), 'issue highlighting must not match nodes by title')
assert(!issueHighlight.includes('node.typeId'), 'issue highlighting must not match nodes by type')
assert(editor.includes('function applyNodeProperties'), 'editor restore must preserve legacy metadata on runtime nodes')
assert(editor.includes('applyNodeProperties(node, item.properties)'), 'restored and pasted nodes must keep legacy port metadata')
assert(editor.includes('function legacyInputsForSnapshot'), 'snapshot must recover legacy input metadata from runtime node ports')
assert(editor.includes('function legacyOutputsForSnapshot'), 'snapshot must recover legacy output metadata from runtime node ports')
assert(platform.includes("'.obp,.vgf,.obpf,.json'"), 'browser open dialog should accept function blueprint files')
assert(platform.includes('LoadProjectSettings'), 'desktop platform should expose project settings loading')
assert(platform.includes('SaveProjectSettings'), 'desktop platform should expose project settings saving')
assert(!platform.includes('StartGraph'), 'platform wrapper should not expose StartGraph while local running is disabled')
assert(!platform.includes('StopGraph'), 'platform wrapper should not expose StopGraph while local running is disabled')
assert(!readme.includes('origin-blueprint-preview.gif'), 'README should not reference the generated preview GIF')
assert(!readme.includes('![OriginBlueprint preview]'), 'README should not show the preview GIF at the top')

console.log('referenceSearchPanel tests passed')
