import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

function assert(value, message) {
  if (!value) throw new Error(message)
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const app = readFileSync(resolve(__dirname, '../src/App.vue'), 'utf8')
const style = readFileSync(resolve(__dirname, '../src/style.css'), 'utf8')
const readme = readFileSync(resolve(__dirname, '../../README.md'), 'utf8')
const node = readFileSync(resolve(__dirname, '../src/editor/BlueprintNode.vue'), 'utf8')
const editor = readFileSync(resolve(__dirname, '../src/editor/createEditor.ts'), 'utf8')
const document = readFileSync(resolve(__dirname, '../src/editor/document.ts'), 'utf8')
const types = readFileSync(resolve(__dirname, '../src/editor/types.ts'), 'utf8')
const platform = readFileSync(resolve(__dirname, '../src/platform.ts'), 'utf8')
const zhCn = readFileSync(resolve(__dirname, '../src/i18n/zh-CN.ts'), 'utf8')
const enUs = readFileSync(resolve(__dirname, '../src/i18n/en-US.ts'), 'utf8')
const issueHighlightStart = editor.indexOf('async function highlightIssueNodes')
const issueHighlightEnd = editor.indexOf('async function highlightIssueNode', issueHighlightStart + 1)
const issueHighlight = issueHighlightStart >= 0 && issueHighlightEnd > issueHighlightStart ? editor.slice(issueHighlightStart, issueHighlightEnd) : ''
const selectGroupStart = editor.indexOf('async function selectGroup')
const selectGroupEnd = editor.indexOf('async function selectConnection', selectGroupStart + 1)
const selectGroupBody = selectGroupStart >= 0 && selectGroupEnd > selectGroupStart ? editor.slice(selectGroupStart, selectGroupEnd) : ''

assert(app.includes('查找目标：{{ nodeReferenceSearch.nodeTitle }}'), 'reference panel must show the searched node title')
assert(!app.includes('class="test-toolbar"'), 'top-right toolbar should not show a duplicate Test button')
assert(!app.includes('class="window-title"'), 'top menu bar should not show the centered Origin Blueprint title')
assert(!app.includes('runGraph'), 'frontend should not keep graph run entrypoints')
assert(!app.includes('stopGraph'), 'frontend should not keep graph stop entrypoints')
assert(!app.includes('executionRunning'), 'frontend should not keep execution running state')
assert(!app.includes('executionLogs'), 'frontend should not keep execution logs')
assert(app.includes('referencePanelCollapsed'), 'reference panel must support collapsing')
assert(app.includes('beginReferencePanelResize'), 'reference panel must support height resizing')
assert(app.includes('beginRightSidebarResize'), 'right sidebar width should be resizable')
assert(app.includes('beginLeftToolsResize'), 'function/variable/detail sidebar width should be resizable next to the canvas')
assert(app.includes('beginVariablePanelHeightResize'), 'variable/detail panels should be vertically resizable')
assert(app.includes('origin-blueprint-right-sidebar-width'), 'right sidebar width should persist locally')
assert(app.includes('origin-blueprint-left-tools-width'), 'function/variable/detail sidebar width should persist locally')
assert(!app.includes('origin-blueprint-function-panel-height'), 'removed function panel should not persist a stale height')
assert(app.includes('origin-blueprint-variable-panel-height'), 'variable panel height should persist locally')
assert(!app.includes('functionPanelStyle'), 'removed function panel should not bind a stale height style')
assert(app.includes('variablePanelStyle'), 'variable panel should bind a persisted height style')
assert(app.includes('interface BlueprintFunction'), 'function panel should have a lightweight function list model')
assert(app.includes('interface FunctionLibraryItem'), 'function library resources should have a lightweight list model')
assert(document.includes('interface FunctionSignature'), 'graph documents should define a function signature model')
assert(document.includes('functionSignature?: FunctionSignature'), 'function signatures should be optional native graph metadata')
assert(app.includes('blueprintFunctions'), 'function panel should keep the current-session function list')
assert(app.includes('functionLibraryItems'), 'app should track function library resources discovered in the workspace')
assert(app.includes('callableFunctionItems'), 'module library should expose callable function placeholders')
assert(app.includes('isFunctionResource'), 'workspace browser should recognize .obpf files and functions folders')
assert(!app.includes('selectWorkspaceFunction'), 'left function panel should not duplicate workspace function resources')
assert(!app.includes('openWorkspaceFunction'), 'workspace function resources should open through the file browser or module library')
assert(!app.includes('revealWorkspaceFunction'), 'workspace function resources should reveal through the file browser menu')
assert(!app.includes('createWorkspaceFunction'), 'workspace function creation should move to the file browser menu')
assert(app.includes('createBlueprintInFileContext'), 'file browser directory menu should create blueprint files')
assert(app.includes('createFunctionInFileContext'), 'file browser directory menu should create function files')
assert(app.includes('joinWorkspacePath(directory, `${graphName}.obpf`)'), 'file browser function creation should target the selected directory')
assert(app.includes('sanitizeFunctionFileName'), 'workspace function file names should be sanitized before saving')
assert(app.includes('functionSignature'), 'app should track the active function signature')
assert(app.includes('isFunctionBlueprintTab'), 'signature editor should only appear for function blueprint files')
assert(app.includes('addFunctionSignaturePort'), 'signature editor should support adding input and output ports')
assert(app.includes('removeFunctionSignaturePort'), 'signature editor should support removing signature ports')
assert(app.includes('normalizeFunctionSignature'), 'opening function files should normalize saved signatures')
assert(app.includes('document.functionSignature ='), 'saving function files should persist the active signature')
assert(app.includes('selectedFunctionId'), 'function selection state should remain available for editor clearing')
assert(app.includes('addBlueprintFunction'), 'current-session function helpers may remain while hidden from the left sidebar')
assert(app.includes('renameBlueprintFunction'), 'current-session function helpers may remain while hidden from the left sidebar')
assert(app.includes('removeBlueprintFunction'), 'current-session function helpers may remain while hidden from the left sidebar')
assert(!app.includes('当前蓝图函数'), 'left sidebar should not show the removed current-blueprint function panel')
assert(!app.includes('class=\"function-row\"'), 'removed function panel should not render function rows')
assert(!app.includes('class=\"add-function\"'), 'removed function panel should not expose an add function button')
assert(app.includes('class=\"workspace-icon function\"'), 'workspace browser should render function resources with a dedicated icon class')
assert(app.includes('class=\"function-library-empty\"'), 'module library should explain when no workspace function library is available')
assert(!app.includes('class=\"function-library-section\"'), 'left function panel should not duplicate workspace function resources')
assert(!app.includes('class=\"function-library-actions\"'), 'left function panel should not render workspace function row actions')
assert(!app.includes('class=\"function-library-panel-empty\"'), 'left function panel should not show a workspace function empty state')
assert(!app.includes('class=\"create-workspace-function\"'), 'left function panel should not show a create workspace function button')
assert(app.includes('function-signature-editor'), 'detail panel should expose a function signature editor')
assert(app.includes('函数签名'), 'function signature editor should be clearly labeled')
assert(!app.includes('@dblclick=\"openWorkspaceFunction(item)\"'), 'workspace function rows should no longer exist in the left panel')
assert(app.includes('category: menuText.value.module.functionCategory'), 'callable functions should appear as a Function category in the module library')
assert(!app.includes('functions:'), 'phase-one function panel must not write functions into GraphDocument yet')
assert(!app.includes('Input Defaults'), 'node detail panel should not show raw input defaults')
assert(editor.includes('setupMultiSelectionDragPreserver'), 'dragging a rubber-band multi-selection should keep the whole node set selected')
assert(editor.includes('restoreMultiSelectionAfterNodePick'), 'node pick should restore an existing multi-selection before dragging')
assert(editor.includes('toggleGroupSelected'), 'editor should expose a single group toggle command for Ctrl+G')
assert(editor.includes('async function clearGroupSelection'), 'editor should centralize clearing stale group selection')
assert(editor.includes('async function selectGroup'), 'selecting a group should switch away from node selection')
assert(editor.includes('function updateGroupSelectionClasses'), 'group selection should update classes without rebuilding group DOM')
assert(selectGroupBody.includes('updateGroupSelectionClasses()'), 'selecting a group should not rebuild the title DOM and break double-click rename')
assert(!selectGroupBody.includes('renderGroups()'), 'selecting a group should preserve the same DOM element so dblclick can fire')
assert(editor.includes('if (nodes.length) { await groupSelected(); return }'), 'Ctrl+G should create a new group when nodes are selected even if an old group selection is stale')
assert(editor.includes('await selector.unselectAll()\n      selectedGroupId = group.id; renderGroups()'), 'creating a group should leave the group selected instead of keeping its member nodes selected')
assert(editor.includes('clearGroupSelection()\n      start = null'), 'rubber-band selection should clear the previous group selection before the next Ctrl+G')
assert(editor.includes('clearGroupSelection()\n      startNodeDragFeedback()'), 'clicking a node should clear the previous group selection')
assert(app.includes('editor?.toggleGroupSelected()'), 'Ctrl+G and the menu should use the group toggle command')
assert(!app.includes('editor?.ungroupSelected())'), 'Ungroup should not require a separate Alt+G menu path')
assert(!app.includes("event.altKey && key === 'g'"), 'Alt+G should not be required for ungrouping selected groups')
assert(app.includes('currentLocale'), 'app should track the active menu locale')
assert(app.includes('menuText'), 'menu template should read labels from the locale file')
assert(app.includes('setLocale'), 'view menu should expose language switching')
assert(app.includes('origin-blueprint-locale'), 'selected menu language should persist locally')
assert(zhCn.includes('显示左侧栏'), 'Chinese view menu should use the shorter left-sidebar label')
assert(!zhCn.includes('显示函数/变量/详情栏'), 'Chinese view menu left-sidebar label should not be overly long')
assert(zhCn.includes('语言'), 'Chinese menu text should include the language section label')
assert(enUs.includes('Show Left Sidebar'), 'English view menu should include the shorter left-sidebar label')
assert(enUs.includes('Language'), 'English menu text should include the language section label')
assert(enUs.includes('File') && enUs.includes('Edit') && enUs.includes('View') && enUs.includes('Blueprint'), 'English locale should define the optimized top-level menu labels')
assert(!enUs.includes('Project'), 'workspace actions should stay in the File menu instead of a top-level Project menu')
assert(enUs.includes("exportSelectedImage: 'Selected Nodes Image'"), 'English file menu should expose selected-node image export as a low-priority file action')
assert(enUs.includes("validate: 'Validate Blueprint'"), 'English blueprint menu should expose validation instead of a top-level Test button')
assert(enUs.includes("about: 'Shortcuts and About'"), 'English help menu should expose the about dialog through a submenu')
assert(app.includes('menuText.menu.file.openWorkspace'), 'file menu should contain the workspace folder action')
assert(app.includes('menuText.menu.file.refreshWorkspace'), 'file menu should contain a workspace refresh action')
assert(app.includes('menuText.menu.file.refreshNodeLibrary'), 'file menu should contain a node library refresh action')
assert(app.indexOf('menuText.menu.file.openWorkspace') < app.indexOf('menuText.menu.file.recent'), 'workspace open should sit near Open before recent files')
assert(app.indexOf('menuText.menu.file.save') < app.indexOf('menuText.menu.file.refreshWorkspace'), 'refresh actions should not interrupt the common Save section')
assert(!app.includes("toggleMenu('project')"), 'workspace actions should not create a dedicated top-level Project menu')
assert(app.includes("toggleMenu('blueprint')"), 'top menu should include a dedicated Blueprint menu')
assert(app.includes("toggleMenu('help')"), 'top menu should render Help as a dropdown menu')
assert(!app.includes("toggleMenu('render')"), 'image export should no longer be a top-level Render menu')
assert(!app.includes('<button @click=\"run(testGraph)\">{{ menuText.menu.test }}</button>'), 'Validate/Test must not remain a standalone top-level button')
assert(app.includes('v-if=\"platform.isDesktop()\"'), 'desktop-only menu actions should be hidden outside the Wails desktop runtime')
assert(app.includes('refreshNodeLibrary'), 'menu should refresh runtime node definitions without restarting the app')
assert(app.includes("ctrl && event.altKey && key === 'r'"), 'selected-node image export shortcut should be wired')
assert(app.includes("ctrl && event.shiftKey && key === 'r'"), 'whole-graph image export shortcut should be wired')
assert(!app.includes('Show Logger'), 'view menu should not show the old English logger label')
assert(!app.includes('Show Tool Sidebar'), 'view menu should not show the old generic tool sidebar label')
assert(!app.includes('Show Right Sidebar'), 'view menu should not show the old generic right sidebar label')
assert(app.includes('openFileContextMenu($event, result)'), 'reference results should open a file context menu on right click')
assert(app.includes('openFileContextMenu($event, row.node)'), 'workspace files and folders should open a file context menu on right click')
assert(app.includes('openFileContextGraph'), 'file context menu should offer opening the blueprint')
assert(app.includes('refreshFileContextDirectory'), 'file context menu should offer refreshing stale workspace directories')
assert(app.includes('refreshWorkspaceDirectory'), 'workspace directory refresh should reload the selected directory contents')
assert(app.includes('ensureWorkspaceChildren(node, workspaceNodeDepth(node.path) + 1, true)'), 'reopening a cached workspace directory should refresh deleted files')
assert(app.includes('refreshWorkspaceVisibleDirectories'), 'workspace browser should refresh already-expanded directories when files change externally')
assert(app.includes('origin-blueprint-workspace-refresh-interval'), 'workspace browser should use a named refresh interval for expanded directories')
assert(app.includes("window.addEventListener('focus', refreshWorkspaceOnFocus)"), 'workspace browser should refresh when the app regains focus after external file deletes')
assert(app.includes('createBlueprintInFileContext'), 'directory context menu should offer creating a blueprint')
assert(app.includes('createFunctionInFileContext'), 'directory context menu should offer creating a function')
assert(app.includes('revealFileContextInFolder'), 'file context menu should offer revealing the file location')
assert(!app.includes('@contextmenu.stop.prevent="revealFileInFolder(result.path)"'), 'reference result right click must not directly reveal files')
assert(!app.includes('@contextmenu.stop.prevent="!row.node.isDir && revealFileInFolder(row.node.path)"'), 'workspace right click must not directly reveal files')

assert(style.includes('.bottom-panel-resizer'), 'reference panel needs a resize handle')
assert(style.includes('.panel-height-splitter'), 'left sidebar panels need visible resize splitters')
assert(style.includes('.right-sidebar-splitter'), 'right sidebar needs a visible resize splitter')
assert(style.includes('.left-tools-splitter'), 'function/variable/detail sidebar needs a canvas resize splitter')
assert(style.includes('var(--right-sidebar-width'), 'workspace grid should use the persisted right sidebar width')
assert(style.includes('var(--left-tools-width'), 'workspace grid should use the persisted function/variable/detail width')
assert(style.includes('.bottom-panel.collapsed'), 'reference panel needs collapsed styling')
assert(style.includes('width: 28px; height: 24px'), 'reference panel controls should be compact but easy to click')
assert(style.includes('.bottom-panel-tool-button.close:hover'), 'close button should have a distinct hover state')
assert(style.includes('.file-context-menu'), 'file context menu needs styling')
assert(style.includes('max-height: calc(100vh - 42px)'), 'dropdown menus should scroll when the window is short')
assert(style.includes('.workspace { min-height: 0; flex: 1; overflow: hidden;'), 'main workspace should clip panels so the file tree can own vertical scrolling')
assert(style.includes('.sidebar { min-width: 0; min-height: 0; overflow: hidden;'), 'sidebars should not grow past the viewport when their content expands')
assert(style.includes('.sidebar-file-browser .workspace-panel { min-height: 0; flex: 1;'), 'file browser panel should shrink to the available sidebar height')
assert(style.includes('.workspace-tree::-webkit-scrollbar'), 'workspace tree should expose a visible scrollbar style')
assert(style.includes('scrollbar-width: thin'), 'workspace tree should show a visible scrollbar in browsers with standard scrollbar styling')
assert(style.includes('scrollbar-gutter: stable'), 'workspace tree should reserve scrollbar space for deep expanded folders')
assert(style.includes('.workspace-icon.function'), 'function resources need a distinct workspace icon')
assert(style.includes('.function-library-empty'), 'function library empty state needs styling')
assert(!style.includes('.function-library-section'), 'removed left function library section should not keep styling')
assert(!style.includes('.function-library-actions'), 'removed workspace function row actions should not keep styling')
assert(!style.includes('.function-library-panel-empty'), 'removed left function library empty state should not keep styling')
assert(style.includes('.function-signature-editor'), 'function signature editor needs styling')
assert(style.includes('.signature-port-row'), 'function signature port rows need styling')

assert(types.includes('referenceHighlighted?: boolean'), 'blueprint nodes need an independent reference highlight state')
assert(!types.includes('executionState'), 'nodes should not keep UI execution state when local running is disabled')
assert(node.includes("'reference-highlighted': data.referenceHighlighted"), 'node template must render reference highlight state')
assert(!node.includes('execution-running'), 'node styles should not keep running highlights when local running is disabled')
assert(node.includes('#ffd21f'), 'reference highlight should use bright yellow for visibility')
assert(!node.includes('.blueprint-node.reference-highlighted { outline: 3px solid #f04444'), 'reference highlight must not reuse the error color')
assert(types.includes('legacyStyle?: boolean'), 'legacy metadata must be separate from legacy visual styling')
assert(node.includes('legacy: Boolean(data.legacyStyle)'), 'legacy styling must use an explicit visual flag')
assert(!node.includes('legacy: Boolean(data.legacyClass)'), 'runtime nodes with legacy metadata must not all render as legacy-styled')
assert(!node.includes('.blueprint-node.legacy { --accent:'), 'legacy compat styling must not override node kind colors')
assert(node.includes('v-if="data.legacyStyle" class="legacy-badge"'), 'compat badge must only render for visually legacy nodes')
assert(editor.includes('node.referenceHighlighted'), 'reference search should mark nodes with the independent highlight state')
assert(!editor.includes('setExecutionStates'), 'editor handle should not expose execution-state updates when local running is disabled')
assert(!editor.includes('for (const node of matches) await selectable.select(node.id, true)'), 'reference search should not rely on selection yellow for highlighting')
assert(editor.includes('const issueHighlightZoomScale'), 'issue highlighting should use a dedicated zoom scale')
assert(editor.includes('const nodeLocateZoomScale'), 'node lookup should use a fixed readable zoom scale')
assert(editor.includes('const nodeLocateMinZoomScale'), 'multi-node lookup should have a readable minimum zoom scale')
assert(editor.includes('const nodeLocateViewportAnchor'), 'node lookup should place targets in the upper reading area')
assert(editor.includes('async function centerNodesForReading'), 'node lookup should center targets without maximizing them')
assert(editor.includes('await centerNodesForReading(matches)'), 'reference lookup should use readable centering')
assert(!issueHighlight.includes('AreaExtensions.zoomAt(area, matches'), 'issue highlighting must not maximize the target nodes')
assert(!issueHighlight.includes('selectable.select'), 'issue highlighting must not select nodes and flash the yellow selection outline')
assert(app.includes('const ids = issueNodeIds(issue)'), 'validation issue selection must derive targets from issue node ids')
assert(app.includes('await editor.highlightIssueNodes([])'), 'running Test must clear stale issue highlights before showing new results')
assert(app.includes('let validationIssueClickTimer'), 'validation issue clicks should be delayed so double-click does not flash single-click selection')
assert(app.includes('clearValidationIssueClickTimer()'), 'validation issue double-click should cancel pending single-click focus')
assert(issueHighlight.includes('const idSet = new Set(ids.filter(Boolean))'), 'issue highlighting must build an exact id set')
assert(issueHighlight.includes('editor.getNodes().filter(node => idSet.has(node.id))'), 'issue highlighting must match node ids exactly')
assert(!issueHighlight.includes('node.label'), 'issue highlighting must not match nodes by title')
assert(!issueHighlight.includes('node.typeId'), 'issue highlighting must not match nodes by type')
assert(editor.includes('function applyNodeProperties'), 'editor restore must preserve legacy metadata on runtime nodes')
assert(editor.includes('applyNodeProperties(node, item.properties)'), 'restored and pasted nodes must keep legacy port metadata')
assert(editor.includes('function legacyInputsForSnapshot'), 'snapshot must recover legacy input metadata from runtime node ports')
assert(editor.includes('function legacyOutputsForSnapshot'), 'snapshot must recover legacy output metadata from runtime node ports')
assert(platform.includes("'.obp,.vgf,.obpf,.json'"), 'browser open dialog should accept function blueprint files')
assert(!platform.includes('StartGraph'), 'platform wrapper should not expose StartGraph while local running is disabled')
assert(!platform.includes('StopGraph'), 'platform wrapper should not expose StopGraph while local running is disabled')
assert(!readme.includes('origin-blueprint-preview.gif'), 'README should not reference the generated preview GIF')
assert(!readme.includes('![OriginBlueprint preview]'), 'README should not show the preview GIF at the top')

console.log('referenceSearchPanel tests passed')
