// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDataFile(arg1) {
  return window['go']['main']['App']['ChooseDataFile'](arg1);
}

export function ChooseExportPNGPath(arg1) {
  return window['go']['main']['App']['ChooseExportPNGPath'](arg1);
}

export function ChooseWorkspace() {
  return window['go']['main']['App']['ChooseWorkspace']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function CurrentWorkingDirectory() {
  return window['go']['main']['App']['CurrentWorkingDirectory']();
}

export function ExportLegacyGraph(arg1) {
  return window['go']['main']['App']['ExportLegacyGraph'](arg1);
}

export function ExportPNG(arg1) {
  return window['go']['main']['App']['ExportPNG'](arg1);
}

export function FindNodeReferences(arg1, arg2) {
  return window['go']['main']['App']['FindNodeReferences'](arg1, arg2);
}

export function ForceSaveGraph(arg1, arg2) {
  return window['go']['main']['App']['ForceSaveGraph'](arg1, arg2);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function ListWorkspace(arg1) {
  return window['go']['main']['App']['ListWorkspace'](arg1);
}

export function LoadNodeSchemaDocuments() {
  return window['go']['main']['App']['LoadNodeSchemaDocuments']();
}

export function LoadProjectSettings(arg1) {
  return window['go']['main']['App']['LoadProjectSettings'](arg1);
}

export function LogClientError(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogClientError'](arg1, arg2, arg3, arg4);
}

export function MigrateLegacyGraph(arg1) {
  return window['go']['main']['App']['MigrateLegacyGraph'](arg1);
}

export function NewWindow() {
  return window['go']['main']['App']['NewWindow']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenGraph(arg1) {
  return window['go']['main']['App']['OpenGraph'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RevealInFolder(arg1) {
  return window['go']['main']['App']['RevealInFolder'](arg1);
}

export function SaveGraph(arg1, arg2) {
  return window['go']['main']['App']['SaveGraph'](arg1, arg2);
}

export function SavePNG(arg1, arg2) {
  return window['go']['main']['App']['SavePNG'](arg1, arg2);
}

export function SaveProjectSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectSettings'](arg1, arg2);
}

export function ValidateGraph(arg1) {
  return window['go']['main']['App']['ValidateGraph'](arg1);
}
