// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDataFile(arg1) {
  return window['go']['main']['App']['ChooseDataFile'](arg1);
}

export function ChooseWorkspace() {
  return window['go']['main']['App']['ChooseWorkspace']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ExportPNG(arg1) {
  return window['go']['main']['App']['ExportPNG'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function ListWorkspace(arg1) {
  return window['go']['main']['App']['ListWorkspace'](arg1);
}

export function LoadNodeSchemaDocuments() {
  return window['go']['main']['App']['LoadNodeSchemaDocuments']();
}

export function MigrateLegacyGraph(arg1) {
  return window['go']['main']['App']['MigrateLegacyGraph'](arg1);
}

export function NewWindow() {
  return window['go']['main']['App']['NewWindow']();
}

export function OpenGraph(arg1) {
  return window['go']['main']['App']['OpenGraph'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveGraph(arg1, arg2) {
  return window['go']['main']['App']['SaveGraph'](arg1, arg2);
}

export function StartGraph(arg1) {
  return window['go']['main']['App']['StartGraph'](arg1);
}

export function StopGraph(arg1) {
  return window['go']['main']['App']['StopGraph'](arg1);
}

export function ValidateGraph(arg1) {
  return window['go']['main']['App']['ValidateGraph'](arg1);
}
