// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseWorkspace() {
  return window['go']['main']['App']['ChooseWorkspace']();
}

export function ExportPNG(arg1) {
  return window['go']['main']['App']['ExportPNG'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function ListWorkspace(arg1) {
  return window['go']['main']['App']['ListWorkspace'](arg1);
}

export function OpenGraph(arg1) {
  return window['go']['main']['App']['OpenGraph'](arg1);
}

export function SaveGraph(arg1, arg2) {
  return window['go']['main']['App']['SaveGraph'](arg1, arg2);
}
