// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseDataFile(arg1:string):Promise<string>;

export function ChooseWorkspace():Promise<string>;

export function ClearRecentFiles():Promise<void>;

export function CurrentWorkingDirectory():Promise<string>;

export function ExportLegacyGraph(arg1:string):Promise<string>;

export function ExportPNG(arg1:string):Promise<string>;

export function FindNodeReferences(arg1:string,arg2:string):Promise<Array<main.NodeReferenceResult>>;

export function GetRecentFiles():Promise<Array<string>>;

export function ListWorkspace(arg1:string):Promise<Array<main.WorkspaceEntry>>;

export function LoadNodeSchemaDocuments():Promise<main.RuntimeNodeSchemaDocumentLoadResult>;

export function LogClientError(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MigrateLegacyGraph(arg1:string):Promise<string>;

export function NewWindow():Promise<void>;

export function OpenGraph(arg1:string):Promise<main.FileResult>;

export function Quit():Promise<void>;

export function RevealInFolder(arg1:string):Promise<void>;

export function SaveGraph(arg1:string,arg2:string):Promise<string>;

export function ValidateGraph(arg1:string):Promise<Array<main.ValidationIssue>>;
